#: include libs/kvs/RoundedShadowButton.kv

#: set btntxtcol 'black'
#: set btncol (1,1,1,1)
#: set btnrad 50
#: set btnfontsize '100sp'
#: set btndowncol (247/255,142/255,48/255,1)
<SmartButton>
    BoxLayout:
        orientation: 'vertical'
        size_hint: None,None
#        size_hint: 1,1
        width: root.width
        height: root.height
        spacing: 3
        padding: 0
        id: main_window
